import { SaveButton } from '@/components/saved-items';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowUpRight, Store, ArrowLeft } from 'lucide-react';
import { products,priceLabel } from '@/data/products';
import { ProductCard,ProductImage } from '@/components/marketplace';
export function generateStaticParams(){return products.map(p=>({slug:p.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=products.find(p=>p.slug===slug);return {title:p?.name??'Item not found',description:p?.description};}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=products.find(p=>p.slug===slug);if(!p)notFound();const related=[...products.filter(x=>x.id!==p.id&&x.category===p.category),...products.filter(x=>x.id!==p.id&&x.category!==p.category)].slice(0,4);const isDemo=new URL(p.externalUrl).hostname==='example.com';return <main id="main" className="container item-page"><Link href="/items" className="text-link back"><ArrowLeft size={16}/> Back to collection</Link><div className="item-detail"><ProductImage key={p.image} src={p.image} name={p.name}/><div className="item-info"><Link className="eyebrow" href={`/items?category=${encodeURIComponent(p.category)}`}>{p.category}</Link><h1>{p.name}</h1><strong className="detail-price">{priceLabel(p.price)}</strong><p className="description">{p.description}</p><div className="seller-box"><Store size={24}/><div><small>SELLER / PLATFORM</small><strong>{p.seller}</strong></div></div><a className="button seller-button" href={p.externalUrl} target="_blank" rel="noopener noreferrer sponsored">View at Seller <ArrowUpRight size={20}/></a><SaveButton id={p.id} name={p.name}/><p className="purchase-note">Purchases are completed on the external seller&apos;s website.</p>{isDemo&&<p className="demo-notice">Example listing: this button opens a placeholder URL, not a purchasable product. Real seller links will be added later.</p>}</div></div><section className="collection"><div className="section-heading"><div><p className="eyebrow">CONTINUE YOUR DISCOVERY</p><h2>You might also like</h2></div></div><div className="product-grid">{related.map(p=><ProductCard key={p.id} product={p}/>)}</div></section></main>;}

