'use client';
import Link from 'next/link';
import { useState } from 'react';
import { Search,X } from 'lucide-react';
import { archiveCategories,archiveEntries,type ArchiveEntry } from '@/data/archive';
import { ProductImage } from './marketplace';
import { ArchiveLike } from './archive-like';
export function ArchiveCard({entry}:{entry:ArchiveEntry}){return <article className="archive-card"><Link href={`/archive/${entry.slug}`} aria-label={`Learn about ${entry.name}`}><ProductImage src={entry.image} name={entry.name}/></Link><div className="archive-card-body"><span className="archive-category">{entry.category}</span><h2><Link href={`/archive/${entry.slug}`}>{entry.name}</Link></h2><p>{entry.shortDescription}</p><div className="archive-card-actions"><Link className="text-link" href={`/archive/${entry.slug}`}>Learn More →</Link><ArchiveLike id={entry.id} name={entry.name}/></div></div></article>;}
export function ArchiveBrowser(){const [query,setQuery]=useState('');const [category,setCategory]=useState('');const [page,setPage]=useState(1);const pageSize=12;
 const filtered=archiveEntries.filter(e=>(!category||e.category===category)&&[e.name,e.category,e.shortDescription,e.overview,e.origin,e.culturalSignificance,...e.facts??[],...e.characteristics??[]].filter(Boolean).join(' ').toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()));const pages=Math.max(1,Math.ceil(filtered.length/pageSize));const current=Math.min(page,pages);
 return <main id="main" className="container archive-page"><section className="archive-intro"><p className="eyebrow">MALAYSIAN DIGITAL ARCHIVE</p><h1>Explore Malaysia&apos;s Living Heritage</h1><p>Discover the objects, food, traditions, places and stories that form Malaysia&apos;s cultural identity.</p></section><div className="catalogue-controls"><label className="filter-search"><Search size={20}/><input aria-label="Search the Archive" placeholder="Search the Archive..." value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}}/>{query&&<button aria-label="Clear Archive search" onClick={()=>{setQuery('');setPage(1);}}><X size={18}/></button>}</label></div><div className="filter-pills" role="group" aria-label="Archive categories"><button type="button" className={!category?'selected':undefined} aria-pressed={!category} onClick={()=>{setCategory('');setPage(1);}}>All Archive</button>{archiveCategories.map(c=><button type="button" key={c} className={category===c?'selected':undefined} aria-pressed={category===c} onClick={()=>{setCategory(c);setPage(1);}}>{c}</button>)}</div><p className="results-meta" role="status">{filtered.length} {filtered.length===1?'entry':'entries'}{category?` in ${category}`:''}</p>{filtered.length?<div className="archive-grid">{filtered.slice((current-1)*pageSize,current*pageSize).map(e=><ArchiveCard key={e.id} entry={e}/>)}</div>:<div className="empty-state"><h2>No archive entries found</h2><p>Try another search or category. This archive is growing.</p><button className="button" onClick={()=>{setQuery('');setCategory('');setPage(1);}}>Reset filters</button></div>}{pages>1&&<nav className="archive-pagination" aria-label="Archive pages"><button disabled={current===1} onClick={()=>setPage(current-1)}>Previous</button><span>Page {current} of {pages}</span><button disabled={current===pages} onClick={()=>setPage(current+1)}>Next</button></nav>}</main>;
}


